"""Schema for LLM-generated spatial proposals."""

from typing import Literal

from pydantic import BaseModel, Field, field_validator


class Proposal(BaseModel):
    """A single spatial hypothesis generated by the proposer LLM.

    The utterance is a concrete, grounded re-phrasing of the original query that
    names exactly one spatial relation and references specific object / region IDs
    from the scene graph.

    Attributes:
        utterance:   Grounded natural-language description, e.g.
                     "the chair near the desk in bedroom-1".
        relation:    Dominant spatial relation used in this hypothesis.
        region_id:   ID of the region (room) where the target is believed to be.
        anchor_ids:  IDs of the anchor object(s) referenced by the relation.
                     Should contain exactly 2 IDs for "between", otherwise 1.
        confidence:  LLM-assigned feasibility score in [0, 1].
    """

    utterance:  str
    relation:   Literal["between", "near", "in", "on", "above", "below"]
    region_id:  int
    anchor_ids: list[int] = Field(min_length=1, max_length=2)
    confidence: float = Field(ge=0.0, le=1.0)

    @field_validator("anchor_ids")
    @classmethod
    def _between_needs_two(cls, v: list[int], info) -> list[int]:
        relation = info.data.get("relation")
        if relation == "between" and len(v) != 2:
            raise ValueError("'between' relation requires exactly 2 anchor_ids")
        if relation != "between" and len(v) != 1:
            raise ValueError(f"relation '{relation}' requires exactly 1 anchor_id")
        return v
